server:
  port: 9000
  servlet:
    context-path: /api

spring:
  sql:
    init:
      mode: always
      continue-on-error: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  profiles:
    active:
      - database
      - jwt
      - cors
      - oauth2
      - ssl
      - file


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.acorn.finals.**
  mapper-locations:
    - classpath:mapper/*.xml

springdoc:
  swagger-ui:
    path: /
    csrf:
      enabled: true

logging:
  level:
    com.acorn.finals: DEBUG
    org.springframework.web: INFO
    org.springframework.core.env.PropertySourcesPropertyResolver: INFO
    com.acorn.finals.mapper: TRACE


