drop table member cascade constraints;
drop table channel cascade constraints;
drop table channel_member cascade constraints;
drop table topic cascade constraints;
drop table message_channel cascade constraints;
drop table message_dm cascade constraints;
drop table direct_message cascade constraints;
drop table refresh_token cascade constraints;
drop table attachment cascade constraints;
drop table request_friend cascade constraints;
drop table friend cascade constraints;

drop sequence member_seq;
drop sequence channel_seq;
drop sequence channel_member_seq;
drop sequence topic_seq;
drop sequence message_channel_seq;
drop sequence message_dm_seq;
drop sequence direct_message_seq;
drop sequence token_seq;
drop sequence attachment_seq;
drop sequence request_friend_seq;
drop sequence friend_seq;
